version: '3.7'
services:
  build:
    container_name: maven_build
    image: maven:3.8.1-jdk-11
      #工作目录空间
    working_dir: /usr/src/mymaven
    volumes:
      - ./:/usr/src/mymaven
      #重用maven库
      - /home/xiaoyouyu/maven/3.8.1-jdk-11/repo:/usr/share/maven/ref/repository
    command: mvn clean package