version: '3.7'
services:
  fruits:
    container_name: fruits_run
    image: maven:3.8.1-jdk-11
    ports:
    - 8081:8081
    environment:
    - FRUITS_MYSQL_USERNAME=${FRUITS_MYSQL_USERNAME}
    - FRUITS_MYSQL_PASSWORD=${FRUITS_MYSQL_PASSWORD}
    - FRUITS_USERNAME=${FRUITS_USERNAME}
    - FRUITS_PASSWORD=${FRUITS_PASSWORD}
    - UPLOAD_VISIT_DOMAIN=${UPLOAD_VISIT_DOMAIN}
    - FRUITS_MINIAPP_APPID=${FRUITS_MINIAPP_APPID}
    - FRUITS_MINIAPP_SECRET=${FRUITS_MINIAPP_SECRET}
    - FRUITS_DOMAIN=${FRUITS_DOMAIN}
    working_dir: /usr/src/fruits
    volumes:
    - /home/liangyu/fruits/0.0.1:/usr/src/fruits
    - /home/liangyu/fruits/0.0.1/upload:/usr/src/fruits/upload
    - /home/liangyu/fruits/0.0.1/log:/usr/src/fruits/log
    - /home/liangyu/fruits/0.0.1/wechat/:/usr/src/fruits/wechat
    command: java -jar ./fruits-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod