version: '3.7'
services:
  run:
    container_name: fruits_run
    image: maven:3.8.1-jdk-11
    ports:
      - 8081:8081
    #工作目录空间
    working_dir: /usr/src/fruits
    volumes:
      - ./:/usr/src/fruits
      #文件上传路径
      - /fruits/upload:/usr/src/fruits/upload
    command: java -jar ./target/fruits-0.0.1-SNAPSHOT.jar