version: '3.7'
services:
  build:
    container_name: maven_build
    image: maven:3.8.1-jdk-11
    ports:
      - 8080:8080
    #工作目录空间
    working_dir: /usr/src/mymaven
    volumes:
      - ./:/usr/src/mymaven
    command: java -jar ./target/fruits-0.0.1-SNAPSHOT.jar