spring:
  application:
    name: fruits
  datasource:
    url: jdbc:mysql://rm-wz97860x6cxc103yi.mysql.rds.aliyuncs.com:3306/fruits?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: ${FRUITS_MYSQL_USERNAME}
    password: ${FRUITS_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: GMT+8
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
server:
  port: 8081

springfox:
  documentation:
    swagger:
      v2:
        enabled: ${SWAGGER_V2_ENABLED}
        host: ${FRUITS_DOMAIN}
    swagger-ui:
      enabled: ${SWAGGER_V2_ENABLED}
fruits:
  admin:
    username: ${FRUITS_USERNAME}
    password: ${FRUITS_PASSWORD}
  upload:
    root-path: /usr/src/fruits/upload
    visit-domain: ${UPLOAD_VISIT_DOMAIN}
  merchant:
    start-time: "2021-08-23 23:59:00"
    end-time: "2021-08-23 23:59:00"
    is-24-hours: false
    is-close: true
logging:
  config: classpath:logback-spring.xml
  file:
    path: /usr/src/fruits/log
wx:
  pay:
    app-id: ${FRUITS_MINIAPP_APPID}
    mch-id: ${FRUITS_WECHAT_MCH_ID}
    apiv3-key: ${FRUITS_WECHAT_APIV3_KEY}
    private-cert-path: /usr/src/fruits/wechat/apiclient_cert.pem
    private-key-path: /usr/src/fruits/wechat/apiclient_key.pem
    pay-score-notify-url: https://api.catchingfire.top/notify/wechat/pay
    refund-notify-url: https://api.catchingfire.top/notify/wechat/refund
  miniapp:
    appid: ${FRUITS_MINIAPP_APPID}
    secret: ${FRUITS_MINIAPP_SECRET}
    token: token
    aes-key: aesKey
    msg-data-format: json
