spring:
  application:
    name: fruits
  datasource:
    url: jdbc:mysql://IP地址:端口/数据库?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: 账号
    password: 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: GMT+8
server:
  port: 8080

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
