spring:
  application:
    name: fruits
  datasource:
    url: jdbc:mysql://IP地址:端口/数据库?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: 账号
    password: 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: GMT+8
  #定时任务
  task:
    execution:
      pool:
        #任务队列已满100时，线程池增加到最多16个线程
        max-size: 16
        queue-capacity: 100

#http服务配置
server:
  port: 8080

#swagger配置
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}

#项目的一些配置
fruits:
  #后台登录账号配置
  admin:
    username: 后台账号
    password: 后台密码
  #上传文件
  upload:
    root-path: D:/javaProject/fruits/upload
    visit-domain: http://fruits.com
#日志配置
logging:
  config: classpath:logback-spring.xml
  #文件路径
  file:
    path: D:/javaProject/fruits/log/

#微信配置
wx:
  #微信支付
  pay:
    app-id: 123
    mch-id: 123
    mch-key: 123
    sub-app-id: 111
    sub-mch-id: 111
    key-path: dddd
  #微信小程序
  miniapp:
    appid: appid
    secret: secret
    token: token
    aes-key: aesKey

