spring:
  application:
    name: fruits
  datasource:
    url: jdbc:mysql://IP地址:端口/数据库?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: 账号
    password: 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson: GMT+8
  #定时任务
  task:
    execution:
      pool:
        #任务队列已满100时，线程池增加到最多16个线程
        max-size: 16
        queue-capacity: 100

#http服务配置
server:
  port: 8080

#swagger配置
springfox:
  documentation:
    swagger:
      v2:
        enabled: true

#项目的一些配置
fruits:
  #后台登录账号配置
  admin:
    username: 后台账号
    password: 后台密码
  #上传文件
  upload:
    root-path: D:/javaProject/fruits/upload
    visit-domain: http://fruits.com
  merchant:
    start-time: "2021-08-23 23:59:00"
    end-time: "2021-08-23 23:59:00"
    is-24-hours: false
    is-close: true
#日志配置
logging:
  config: classpath:logback-spring.xml
  #文件路径
  file:
    path: D:/javaProject/fruits/log/

#微信配置
wx:
  #微信支付
  pay:
    app-id: #微信公众号或者小程序等appid
    mch-id: #微信支付商户号
    mch-key: #微信支付商户秘钥
    sub-app-id: #服务商模式下的子商户公众号id
    sub-mch-id: #服务商模式下的字商户号
    key-path: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
  #微信小程序
  miniapp:
    appid: appid
    secret: secret
    token: token
    aes-key: aesKey
    msg-data-format: json

#mybati-plus配置
mybatis-plus:
  configuration:
    #sql日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
